# Generated by Django 3.1.4 on 2021-01-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
