# Generated by Django 3.1.4 on 2021-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
