# Generated by Django 3.1.4 on 2021-01-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Dummy Studio', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=150),
        ),
    ]
